In [10]:
import pandas as pd
import json
import requests
from dotenv import load_dotenv, find_dotenv
import os

load_dotenv(find_dotenv("local_keys.env"))

True

In [11]:
eia_key = os.getenv("eia")

In [12]:
type(eia_key)

str

In [13]:
url = f"https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?api_key={eia_key}&frequency=quarterly&data[0]=consumption-for-eg-btu&facets[fueltypeid][]=ALL&facets[sectorid][]=99&facets[location][]=ENC&facets[location][]=ESC&facets[location][]=MAT&facets[location][]=MTN&facets[location][]=PCC&facets[location][]=PCN&facets[location][]=SAT&start=2001-Q1&end=2024-Q3&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"

In [14]:
eia_response = requests.get(url)

In [15]:
eia_data = eia_response.json()

In [16]:
# print(json.dumps(eia_data, indent=4))

In [23]:
energy = pd.json_normalize(eia_data)
df_energy = energy.explode("response.data")
df_energy.head()

,apiVersion,ExcelAddInVersion,response.total,response.dateFormat,response.frequency,response.data,response.description,request.command,request.params.api_key,request.params.frequency,request.params.data,request.params.facets.fueltypeid,request.params.facets.sectorid,request.params.facets.location,request.params.start,request.params.end,request.params.sort,request.params.offset,request.params.length
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2024-Q2', 'location': 'MTN', 'stateDescription': 'Mountain', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '620.10123', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2024-Q2', 'location': 'MAT', 'stateDescription': 'Middle Atlantic', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '851.66501', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2024-Q2', 'location': 'ESC', 'stateDescription': 'East South Central', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '779.44791', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2024-Q2', 'location': 'PCC', 'stateDescription': 'Pacific Contiguous', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '449.4703', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2024-Q2', 'location': 'SAT', 'stateDescription': 'South Atlantic', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '1792.82698', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2001-Q1', 'location': 'PCC', 'stateDescription': 'Pacific Contiguous', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '873.31', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2001-Q1', 'location': 'ESC', 'stateDescription': 'East South Central', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '941.496', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2001-Q1', 'location': 'MTN', 'stateDescription': 'Mountain', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '827.079', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2001-Q1', 'location': 'SAT', 'stateDescription': 'South Atlantic', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '1856.112', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000
0,2.1.7,2.1.0,462,"YYYY-""Q""Q",quarterly,"{'period': '2001-Q1', 'location': 'ENC', 'stateDescription': 'East North Central', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '1630.509', 'consumption-for-eg-btu-units': 'million MMBtu'}","Monthly and annual electric power operations by state, sector, and energy source.\n Source: Form EIA-923",/v2/electricity/electric-power-operational-data/data/,ef9ylDxtxjwKzq7UZOH23iroZkUbi0PicRCovfF0,quarterly,[consumption-for-eg-btu],[ALL],[99],"[ENC, ESC, MAT, MTN, PCC, PCN, SAT]",2001-Q1,2024-Q3,"[{'column': 'period', 'direction': 'desc'}]",0,5000

In [18]:
pd.set_option('display.max_colwidth', None)
energy_data = df_energy[['response.data']].reset_index().drop(columns='index').rename(columns={'response.data': 'data'})
energy_data.head()

                                                                                                                                                                                                                                                                                        data
0            {'period': '2024-Q2', 'location': 'MTN', 'stateDescription': 'Mountain', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '620.10123', 'consumption-for-eg-btu-units': 'million MMBtu'}
1     {'period': '2024-Q2', 'location': 'MAT', 'stateDescription': 'Middle Atlantic', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '851.66501', 'consumption-for-eg-btu-units': 'million MMBtu'}
2  {'period': '2024-Q2', 'location': 'ESC', 'stateDescription': 'East South Central', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '779.44791', 'consumption-for-eg-btu-units': 'million MMBtu'}
3   {'period': '2024-Q2', 'location': 'PCC', 'stateDescription': 'Pacific Contiguous', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '449.4703', 'consumption-for-eg-btu-units': 'million MMBtu'}
4     {'period': '2024-Q2', 'location': 'SAT', 'stateDescription': 'South Atlantic', 'sectorid': '99', 'sectorDescription': 'All Sectors', 'fueltypeid': 'ALL', 'fuelTypeDescription': 'all fuels', 'consumption-for-eg-btu': '1792.82698', 'consumption-for-eg-btu-units': 'million MMBtu'}

In [34]:
energy_df = energy_data['data'].apply(pd.Series)
energy_df['period'] = pd.to_datetime(energy_df['period'])
energy_df.head()

C:\Users\jpdav\AppData\Local\Temp\ipykernel_192820\2260977964.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  energy_df['period'] = pd.to_datetime(energy_df['period'])

,period,location,stateDescription,sectorid,sectorDescription,fueltypeid,fuelTypeDescription,consumption-for-eg-btu,consumption-for-eg-btu-units
0,2024-04-01,MTN,Mountain,99,All Sectors,ALL,all fuels,620.10123,million MMBtu
1,2024-04-01,MAT,Middle Atlantic,99,All Sectors,ALL,all fuels,851.66501,million MMBtu
2,2024-04-01,ESC,East South Central,99,All Sectors,ALL,all fuels,779.44791,million MMBtu
3,2024-04-01,PCC,Pacific Contiguous,99,All Sectors,ALL,all fuels,449.4703,million MMBtu
4,2024-04-01,SAT,South Atlantic,99,All Sectors,ALL,all fuels,1792.82698,million MMBtu

In [36]:

final_energy = energy_df.drop(columns=['sectorid', 'stateDescription', 'sectorDescription', 'fueltypeid', 'fuelTypeDescription', 'consumption-for-eg-btu-units']).reset_index().drop(columns='index')
final_energy = final_energy.rename(columns={'period':'Date', 'location':'Region', 'consumption-for-eg-btu':'Energy in mmBTU'})
final_energy.head()

        Date Region Energy in mmBTU
0 2024-04-01    MTN       620.10123
1 2024-04-01    MAT       851.66501
2 2024-04-01    ESC       779.44791
3 2024-04-01    PCC        449.4703
4 2024-04-01    SAT      1792.82698

In [1]:
!pip install openmeteo-requests
!pip install requests-cache retry-requests numpy pandas

Collecting openmeteo-requests
  Downloading openmeteo_requests-1.3.0-py3-none-any.whl.metadata (9.7 kB)
Collecting openmeteo-sdk>=1.4.0 (from openmeteo-requests)
  Downloading openmeteo_sdk-1.16.0-py3-none-any.whl.metadata (934 bytes)
Requirement already satisfied: requests in c:\users\hollidaydds\anaconda3\lib\site-packages (from openmeteo-requests) (2.32.2)
Collecting flatbuffers>=24.0.0 (from openmeteo-sdk>=1.4.0->openmeteo-requests)
  Downloading flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests->openmeteo-requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests->openmeteo-requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests->openmeteo-requests) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests->openmeteo-requests) (2024.6.2)
Downloading openmeteo_requests-1.3.0-py3-none-any.whl (6.0 kB)
Downloading openmeteo_sdk-1.16.0-py3-none-any.whl (7.5 kB)
Downloading flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Installing collected packages: flatbuffers, openmeteo-sdk, openmeteo-requests
Successfully installed flatbuffers-24.3.25 openmeteo-requests-1.3.0 openmeteo-sdk-1.16.0
Collecting requests-cache
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Collecting retry-requests
  Downloading retry_requests-2.0.0-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy in c:\users\hollidaydds\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: pandas in c:\users\hollidaydds\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: attrs>=21.2 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests-cache) (23.1.0)
Collecting cattrs>=22.2 (from requests-cache)
  Downloading cattrs-24.1.2-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests-cache) (3.10.0)
Requirement already satisfied: requests>=2.22 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests-cache) (2.32.2)
Collecting url-normalize>=1.4 (from requests-cache)
  Downloading url_normalize-1.4.3-py2.py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: urllib3>=1.25.5 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests-cache) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hollidaydds\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hollidaydds\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hollidaydds\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\hollidaydds\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests>=2.22->requests-cache) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests>=2.22->requests-cache) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hollidaydds\anaconda3\lib\site-packages (from requests>=2.22->requests-cache) (2024.6.2)
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
Downloading retry_requests-2.0.0-py3-none-any.whl (15 kB)
Downloading cattrs-24.1.2-py3-none-any.whl (66 kB)
Downloading url_normalize-1.4.3-py2.py3-none-any.whl (6.8 kB)
Installing collected packages: url-normalize, cattrs, retry-requests, requests-cache
Successfully installed cattrs-24.1.2 requests-cache-1.2.1 retry-requests-2.0.0 url-normalize-1.4.3

In [2]:
import openmeteo_requests

import requests_cache
import pandas as pd
from retry_requests import retry

# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession('.cache', expire_after = -1)
retry_session = retry(cache_session, retries = 5, backoff_factor = 0.2)
openmeteo = openmeteo_requests.Client(session = retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"
params = {
	"latitude": 52.52,
	"longitude": 13.41,
	"start_date": "2000-01-01",
	"end_date": "2009-12-31",
	"hourly": ["temperature_2m", "relative_humidity_2m", "precipitation"],
	"temperature_unit": "fahrenheit",
	"wind_speed_unit": "mph",
	"precipitation_unit": "inch"
}
responses = openmeteo.weather_api(url, params=params)

# Process first location. Add a for-loop for multiple locations or weather models
response = responses[0]
print(f"Coordinates {response.Latitude()}°N {response.Longitude()}°E")
print(f"Elevation {response.Elevation()} m asl")
print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

# Process hourly data. The order of variables needs to be the same as requested.
hourly = response.Hourly()
hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
hourly_precipitation = hourly.Variables(2).ValuesAsNumpy()

hourly_data = {"date": pd.date_range(
	start = pd.to_datetime(hourly.Time(), unit = "s", utc = True),
	end = pd.to_datetime(hourly.TimeEnd(), unit = "s", utc = True),
	freq = pd.Timedelta(seconds = hourly.Interval()),
	inclusive = "left"
)}
hourly_data["temperature_2m"] = hourly_temperature_2m
hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
hourly_data["precipitation"] = hourly_precipitation

hourly_dataframe = pd.DataFrame(data = hourly_data)

Coordinates 52.5483283996582°N 13.407821655273438°E
Elevation 38.0 m asl
Timezone None None
Timezone difference to GMT+0 0 s
                           date  temperature_2m  relative_humidity_2m  \
0     2000-01-01 00:00:00+00:00       31.890200             96.781876
1     2000-01-01 01:00:00+00:00       31.620199             96.777954
2     2000-01-01 02:00:00+00:00       31.890200             96.430031
3     2000-01-01 03:00:00+00:00       31.710199             96.076157
4     2000-01-01 04:00:00+00:00       31.620199             96.074577
...                         ...             ...                   ...
87667 2009-12-31 19:00:00+00:00       28.290199             85.533020
87668 2009-12-31 20:00:00+00:00       27.930201             85.832748
87669 2009-12-31 21:00:00+00:00       27.840200             85.827271
87670 2009-12-31 22:00:00+00:00       27.570200             86.784798
87671 2009-12-31 23:00:00+00:00       27.390200             87.429741

       precipitation
0           0.000000
1           0.000000
2           0.000000
3           0.000000
4           0.000000
...              ...
87667       0.007874
87668       0.007874
87669       0.007874
87670       0.011811
87671       0.015748

[87672 rows x 4 columns]

In [3]:
hourly_dataframe.head()

,date,temperature_2m,relative_humidity_2m,precipitation
0,2000-01-01 00:00:00+00:00,31.890200,96.781876,0.0
1,2000-01-01 01:00:00+00:00,31.620199,96.777954,0.0
2,2000-01-01 02:00:00+00:00,31.890200,96.430031,0.0
3,2000-01-01 03:00:00+00:00,31.710199,96.076157,0.0
4,2000-01-01 04:00:00+00:00,31.620199,96.074577,0.0